### ISSUE TITLE
deposit

### ISSUE THREAD

**Issue by CPernet** [openneuropet/templates#1]
@melanieganz @mnoergaard could you deposit in the the Serotonin and BZR/GABAa templates

+++ what licence to use?

**Comment by mnoergaard** [comment]
Current license: All rights reserved according to CC 4.0 BY-NC-SA (https://creativecommons.org/licenses/by-nc-sa/4.0). Redistribution and use in source forms, with or without modification, are permitted provided that the following conditions are met: * You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use. * You may not use the material for commercial purposes. Neither the name of the Neurobiology Research Unit, Rigshospital nor the names of its contributors may be used to endorse or promote products derived from this image set without specific prior written permission. * If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.

**Comment by CPernet** [comment]
is that also the one @melanieganz used in EBRAIN for serotonin? we need to be consistent (and compatible if used another one)
